name: Java CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch
  push:
    tags:
      - 'v*'  # Trigger the workflow on tags starting with 'v' (for any tab use "*")

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Check out your repository's code

      - name: Set Up JDK  # Set up Java Development Kit (JDK) 
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the JDK version (e.g., Java 11)

      - name: Build with Maven  # Build the Java project using Apache Maven
        run: mvn clean install  # Replace with your Maven build command

      - name: Run Tests  # Run tests
        run: mvn test  # Replace with your Maven test command

      - name: Package JAR  # Package your Java application (e.g., create a JAR file)
        run: mvn package  # Replace with your Maven package command

deploy:
    #  The job or step will run when you push a Git tag starting with 'v'.
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Server  # Example: Deploy your Java application to a server
        if: startsWith(github.ref, 'refs/tags/v') # github.ref is an environment variable provided by GitHub Actions. 
        # It contains the full Git ref (reference) associated with the event that triggered the workflow.
        # In this context, it typically holds the Git tag reference when a tag push event triggers the workflow.
        ....